### ISSUE TITLE
Latest release tarball does not build

### ISSUE THREAD

**Issue by bentley** [apertium/apertium-kaz-tat#1]
The latest release, 0.2.1, does not build:

    hfst-lexc --format foma .deps/kaz.RL.lexc -o .deps/kaz.RL.lexc.hfst
    Root...18 CASE-NONOM...6 CASE-ETC-NONOM...2 N-INFL-COMMON-NONOM...2 SUBST-NONOM...2 SQRD...3 NUM-DIGIT...19 LASTDIGIT...9 LASTDIGIT-REST...9 POWERS...2 LOOP...12 DIGITLEX...10 SUBST...2 CLIT-EMPH...2 CLIT-QST-MA...1 CLIT-QST...3 CLIT-MODASS...2 CLIT-GHANA-ETC...5 CLIT-COPULA...1 CLITICS...3 CLITICS-INCLUDING-COPULA...2 CASE-COMMON...4 CASE...4 CASE-2...4 ATTR/SUBST...3 ABE-ATTR/ADVL/SUBST...4 Abessive...1 GENPOSS-ETC...3 CASE-ETC...2 POSS-REAL...7 POSSESSION...1 N-INFL-COMMON...3 COMPARATIVE...2 A1...6 A2...4 A3...2 A4...1 V-ADJ...2 V-PERS-S1-NO3PERSON...6 V-PERS-S1...3 V-PERS-S2...8 V-PERS-AOR...3 V-PERS-IFI_EVID...3 VOL-ENDINGS...8 GER-CASE-NO_COPULA...4 GER-ATTR/SUBST...1 GER-ABE-ATTR/ADVL/SUBST...1 GER-ABE-ETC...1 GER-GENPOSS-ETC...3 GER-CASE-ETC...2 GER-POSS-REAL...7 GER-INFL...5 V-FINITE-IRREGULAR_NEGATIVE...2 V-FINITE-REGULAR_NEGATIVE...5 V-NONFINITE-IRREGULAR_NEGATIVE...17 V-NONFINITE-REGULAR_NEGATIVE...19 V-COMMON...6 V-DER...1 V-TV-NOPASS...2 V-TV-PASS...1 V-TV...3 V-IV...2 Vinfl-AUX-IMPF...1 Vinfl-AUX...1 Copula...6 PRON-12SG-CASES...10 PRON-PERS-INFL...1 PersonalPronouns...25 PRON-DEM-INFL...12 PRON-DEM-BUL...18 PRON-DEM-MINA...12 PRON-DEM-ANA...12 DemonstrativePronouns...15 PRON-ITG-INFL...1 PRON-ITG-QAYSI...8 PRON-ITG-QANSHA...1 PRON-ITG-QANDAY...5 InterrogativePronouns...6 PRON-QNT-POSS...1 PRON-QNT...1 PRON-IND...1 PRNNEG...1 PRON-RECIP...1 PRON-REF-ADV...2 PRON-REF...8 DET-DEM...1 DET-QNT...1 DET-IND...1 DET-ITG...1 DET-NEG...1 DET-REF...1 N1-ABBR...3 N1...2 N-COMPOUND-PX-COMMON...2 N-COMPOUND-PX...2 N3...2 N5...1 ADV-LANG...2 NP-COMMON...1 NP-TOP...2 NP-ANT-M...2 NP-ANT-F...2 NP-COG-M...2 NP-COG-MF...2 NP-COG-OBIN-FEM...2 NP-COG-OB...3 NP-COG-IN...3 NP-PAT-VICH...2 NP-ORG...1 NP-ORG-COMPOUND...1 NP-AL...1 NUM-COMMON...2 NUM...3 NUM-TWENTY...2 NUM-ITG...3 NUM-COLL...2 NUM-ROMAN...
    .deps/kaz.RL.lexc:1437.1-17: Sublexicon defined more than once.: [near: `LEXICON DIGITLEX']
    hfst-lexc: The file .deps/kaz.RL.lexc did not compile cleanly.
    (if there are no error messages above, try -v or -d to get more info)
    gmake: *** [Makefile:666: .deps/kaz.RL.lexc.hfst] Error 1

Is there a chance of a new release anytime soon? (Would this necessitate releases of apertium-kaz and apertium-tat also?)

**Comment by TinoDidriksen** [comment]
Almost all pair releases also require a release of their single language dependencies.
